# Generated by Django 5.1.3 on 2024-12-10 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits.', regex='^\\d{9,15}$')])),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('mypay_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('working_date', models.DateTimeField()),
                ('session', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('waiting', 'Waiting For Worker to Depart'), ('arrived', 'Arrived At Location'), ('working', 'Providing Service'), ('completed', 'Service Completed'), ('cancelled', 'Order Cancelled')], default='others', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('level', models.CharField(default='Standard', max_length=50)),
            ],
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.user')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('npwp', models.CharField(max_length=20, unique=True)),
                ('avatar_url', models.URLField()),
                ('rate', models.FloatField(default=0.0)),
                ('total_finish_order', models.IntegerField(default=0)),
            ],
            bases=('main.user',),
        ),
    ]
